import httpx
from app.core.config import settings

class LLMGateway:
    async def generate(self, system: str, prompt: str) -> str:
        # Safe runnable default: deterministic local output; configure an OpenAI-compatible provider in production.
        if settings.llm_provider == "mock" or not settings.llm_base_url:
            return self._mock(system, prompt)
        headers={"Authorization": f"Bearer {settings.llm_api_key}"}
        payload={"model":settings.llm_model,"messages":[{"role":"system","content":system},{"role":"user","content":prompt}],"temperature":0.4}
        async with httpx.AsyncClient(timeout=60) as c:
            r=await c.post(settings.llm_base_url.rstrip("/")+"/chat/completions",json=payload,headers=headers)
            r.raise_for_status()
            return r.json()["choices"][0]["message"]["content"]

    def _mock(self, system: str, prompt: str) -> str:
        topic = prompt.split("TOPIC:")[-1].splitlines()[0].strip() if "TOPIC:" in prompt else "the requested topic"
        return f"{topic}\n\nA structured, evidence-aware draft generated by ContentAlchemy. Configure an LLM provider for production-quality generation.\n\nKey idea: make the content useful, specific, credible, and appropriate for its intended audience."
